language: go

env:
  - GO111MODULE=on

go:
  # - 1.10.x
  - 1.11.x
  # - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out ./...

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
